version: '3.3'

services:
    app:
        build: .
        image: mlopsapp:latest
        ports:
          - 8000:8000
        volumes:
          - '.:/app'
        command: "python3 run.py"
    mlflow:
        image: mlopsapp:latest
        ports:
          - 5000:5000
        volumes:
          - '.:/app'
        command: "mlflow ui --host 0.0.0.0"
